import streamlit as st
import pandas as pd
import csv
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from matcher import search_amazon

st.set_page_config(page_title="Amazon Matcher", layout="wide")

st.title("🛒 Amazon Title → ASIN Matcher")
st.write("Paste titles or upload a CSV file")

# --------------------------------------------------
# Helper: Detect CSV delimiter automatically
# --------------------------------------------------
def detect_delimiter(uploaded_file):
    sample = uploaded_file.read(5000).decode("utf-8", errors="ignore")
    uploaded_file.seek(0)

    try:
        dialect = csv.Sniffer().sniff(sample)
        return dialect.delimiter
    except:
        return ","


# --------------------------------------------------
# Helper: Clean brand text
# --------------------------------------------------
def clean_brand_text(brand_text, strings_to_remove):
    if pd.isna(brand_text):
        return ""

    cleaned = str(brand_text)

    for s in strings_to_remove:
        s = s.strip()
        if s:
            cleaned = cleaned.replace(s, "")

    return " ".join(cleaned.split()).strip()


# --------------------------------------------------
# TEXT INPUT OPTION
# --------------------------------------------------
text_input = st.text_area("Product titles (one per line)")

# --------------------------------------------------
# CSV UPLOAD OPTION
# --------------------------------------------------
uploaded_file = st.file_uploader("OR upload CSV", type=["csv"])

df = None
title_column = None

advanced_brand_search = False
brand_column = None
brand_strings_to_remove_raw = ""
wrap_brand_in_quotes = True

if uploaded_file:

    detected_delimiter = detect_delimiter(uploaded_file)

    delimiter = st.selectbox(
        "CSV delimiter",
        options=[",", ";", "|", "\t"],
        index=[",", ";", "|", "\t"].index(detected_delimiter)
        if detected_delimiter in [",", ";", "|", "\t"]
        else 0
    )

    df = pd.read_csv(uploaded_file, delimiter=delimiter)

    st.success(f"Detected delimiter: '{detected_delimiter}'")

    title_column = st.selectbox(
        "Select column containing product titles",
        df.columns.tolist()
    )

    advanced_brand_search = st.checkbox(
        "Advanced search: include brand in title query",
        value=False
    )

    if advanced_brand_search:
        brand_column = st.selectbox(
            "Select column containing brand",
            df.columns.tolist()
        )

        brand_strings_to_remove_raw = st.text_area(
            "Strings to remove from brand text (one per line)",
            placeholder="Example:\ncsv file generated by Mirko csv\n|\nCompany srl"
        )

        wrap_brand_in_quotes = st.checkbox(
            'Wrap brand in quotes (") for exact brand search',
            value=True
        )

    st.write("Preview:")
    st.dataframe(df.head(), use_container_width=True)

# --------------------------------------------------
# SETTINGS
# --------------------------------------------------
top_n = st.slider("Results per title", 1, 10, 5)

st.subheader("⚙ Scan Options")

parallel_scan = st.checkbox("Enable parallel scan (faster)", value=False)
safe_mode = st.checkbox("Safe mode (slow but safest)", value=True)
use_cache = st.checkbox("Enable result cache", value=True)

cache = {}

# --------------------------------------------------
# SEARCH WRAPPER
# --------------------------------------------------
def run_search(title):

    if use_cache and title in cache:
        return cache[title]

    # Safe mode delay (prevents throttling)
    if safe_mode:
        time.sleep(0.6)

    result = search_amazon(title, top_n)

    if use_cache:
        cache[title] = result

    return result


# --------------------------------------------------
# RUN BUTTON
# --------------------------------------------------
if st.button("Run Matching"):

    results_rows = []
    progress = st.progress(0)

    # -------- TEXT MODE --------
    if text_input and df is None:

        titles = [t.strip() for t in text_input.split("\n") if t.strip()]

        for i, title in enumerate(titles):

            matches = run_search(title)

            for match in matches:
                results_rows.append({
                    "input_title": title,
                    "matched_asin": match["asin"],
                    "amazon_title": match["title"],
                    "brand": match["brand"],
                    "image": match["image"],
                    "scan_parallel": parallel_scan,
                    "safe_mode": safe_mode,
                    "cache_enabled": use_cache
                })

            progress.progress((i + 1) / len(titles))

    # -------- CSV MODE --------
    elif df is not None and title_column:

        rows = list(df.iterrows())

        def process_row(item):
            _, row = item
            title = str(row[title_column]).strip()

            search_query = title
            raw_brand = ""
            cleaned_brand = ""

            if advanced_brand_search and brand_column:
                raw_brand = str(row[brand_column]) if pd.notna(row[brand_column]) else ""

                strings_to_remove = [
                    s.strip()
                    for s in brand_strings_to_remove_raw.split("\n")
                    if s.strip()
                ]

                cleaned_brand = clean_brand_text(raw_brand, strings_to_remove)

                if cleaned_brand:
                    if wrap_brand_in_quotes:
                        search_query = f'{title} "{cleaned_brand}"'
                    else:
                        search_query = f"{title} {cleaned_brand}"

            matches = run_search(search_query)

            output = []

            for match in matches:
                new_row = row.to_dict()

                new_row.update({
                    "search_query_used": search_query,
                    "source_brand_raw": raw_brand,
                    "source_brand_cleaned": cleaned_brand,
                    "brand_wrapped_in_quotes": wrap_brand_in_quotes if advanced_brand_search else False,
                    "advanced_brand_search": advanced_brand_search,

                    "matched_asin": match["asin"],
                    "amazon_title": match["title"],
                    "brand": match["brand"],
                    "image": match["image"],
                    "scan_parallel": parallel_scan,
                    "safe_mode": safe_mode,
                    "cache_enabled": use_cache
                })

                output.append(new_row)

            return output

        # ---------- PARALLEL MODE ----------
        if parallel_scan and not safe_mode:

            with ThreadPoolExecutor(max_workers=5) as executor:
                futures = [executor.submit(process_row, r) for r in rows]

                for idx, future in enumerate(as_completed(futures)):
                    results_rows.extend(future.result())
                    progress.progress((idx + 1) / len(rows))

        # ---------- SAFE / NORMAL MODE ----------
        else:
            for idx, r in enumerate(rows):
                results_rows.extend(process_row(r))
                progress.progress((idx + 1) / len(rows))

    else:
        st.warning("Please provide titles or upload a CSV.")
        st.stop()

    # --------------------------------------------------
    # OUTPUT
    # --------------------------------------------------
    result_df = pd.DataFrame(results_rows)

    st.success("Matching completed!")

    result_df_display = result_df.copy()

    result_df_display["image_preview"] = result_df_display["image"].apply(
        lambda x: f'<img src="{x}" width="120">' if pd.notnull(x) and x else ""
    )

    st.markdown(
        result_df_display.drop(columns=["image"]).to_html(escape=False, index=False),
        unsafe_allow_html=True
    )

    csv_download = result_df.to_csv(index=False).encode("utf-8")

    st.download_button(
        "⬇ Download Results CSV",
        csv_download,
        "amazon_matches.csv",
        "text/csv"
    )
